// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logInOut.proto

#include "logInOut.pb.h"
#include "logInOut.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace RPC {

static const char* UserServiceRPC_method_names[] = {
  "/RPC.UserServiceRPC/Login",
  "/RPC.UserServiceRPC/Register",
};

std::unique_ptr< UserServiceRPC::Stub> UserServiceRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserServiceRPC::Stub> stub(new UserServiceRPC::Stub(channel, options));
  return stub;
}

UserServiceRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(UserServiceRPC_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(UserServiceRPC_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserServiceRPC::Stub::Login(::grpc::ClientContext* context, const ::RPC::LoginRequest& request, ::RPC::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RPC::LoginRequest, ::RPC::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void UserServiceRPC::Stub::async::Login(::grpc::ClientContext* context, const ::RPC::LoginRequest* request, ::RPC::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RPC::LoginRequest, ::RPC::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void UserServiceRPC::Stub::async::Login(::grpc::ClientContext* context, const ::RPC::LoginRequest* request, ::RPC::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RPC::LoginResponse>* UserServiceRPC::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::RPC::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RPC::LoginResponse, ::RPC::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RPC::LoginResponse>* UserServiceRPC::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::RPC::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserServiceRPC::Stub::Register(::grpc::ClientContext* context, const ::RPC::RegisterRequest& request, ::RPC::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RPC::RegisterRequest, ::RPC::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void UserServiceRPC::Stub::async::Register(::grpc::ClientContext* context, const ::RPC::RegisterRequest* request, ::RPC::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RPC::RegisterRequest, ::RPC::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void UserServiceRPC::Stub::async::Register(::grpc::ClientContext* context, const ::RPC::RegisterRequest* request, ::RPC::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RPC::RegisterResponse>* UserServiceRPC::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::RPC::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RPC::RegisterResponse, ::RPC::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RPC::RegisterResponse>* UserServiceRPC::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::RPC::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserServiceRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServiceRPC::Service, ::RPC::LoginRequest, ::RPC::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserServiceRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RPC::LoginRequest* req,
             ::RPC::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceRPC_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServiceRPC::Service, ::RPC::RegisterRequest, ::RPC::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserServiceRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RPC::RegisterRequest* req,
             ::RPC::RegisterResponse* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
}

UserServiceRPC::Service::~Service() {
}

::grpc::Status UserServiceRPC::Service::Login(::grpc::ServerContext* context, const ::RPC::LoginRequest* request, ::RPC::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserServiceRPC::Service::Register(::grpc::ServerContext* context, const ::RPC::RegisterRequest* request, ::RPC::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace RPC

